version: '3.9'
services:
  node-server:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
    env_file:
      - ./.env
  db:
    image: 'postgres'
    ports:
      - "4321:5432"
    environment:
      POSTGRES_PASSWORD: "Blaise1..."
      POSTGRES_USER: "awesomety"
    env_file:
      - ./.env
    volumes:
      - data:/var/lib/postgresql/data
    
volumes:
  data:
